dubbo:
  application:
    name: dubbo-test
    owner: luhanlin
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://127.0.0.1:2181
    check: true
    group: dubbo-test
    simplified: true
  metadata-report:
    address: zookeeper://127.0.0.1:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-test
  scan:
    base-packages: com.luhanlin.practice
